---
booktitle: 29th Annual Conference on Learning Theory
shortname: COLT
year: '2016'
volume: 49
published: 2016-06-06
start: 2016-06-23
end: 2016-06-26
sections:
- name: preface
  title: Preface
- name: default
  title: Regular Papers
- name: open
  title: Open Problems
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: COLT2016
month: 0
cycles: false
editor:
- given: Vitaly
  family: Feldman
- given: Alexander
  family: Rakhlin
- given: Ohad
  family: Shamir
title: Proceedings of Machine Learning Research
description: |
  29th Annual Conference on Learning Theory
    Held in Columbia University, New York, New York, USA on 23-26 June 2016

  Published as Volume 49 by the Proceedings of Machine Learning Research on 06 June 2016.

  Volume Edited by:
    Vitaly Feldman
    Alexander Rakhlin
    Ohad Shamir

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 23--26 Jun
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v49"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v49
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Conference on Learning Theory
  url: http://www.learningtheory.org/colt2016/
  location: Columbia University, New York, New York, USA
  dates:
  - 2016-06-23
  - 2016-06-24
  - 2016-06-25
  - 2016-06-26
  number: 29
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
